# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_content', models.CharField(max_length=255, verbose_name='public')),
                ('private_content', models.CharField(max_length=255, verbose_name='private')),
                ('permission_content', models.CharField(max_length=255, verbose_name='private')),
            ],
            options={
                'permissions': (('can_view', 'Can see content'),),
            },
        ),
    ]
